# -*- coding: utf-8 -*-
"""Multiple Linear Regression Stock Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2ax1dpEkJt0hTbpgG9KyzAqpgJ7L8xR
"""

import operator

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

from google.colab import files
uploaded = files.upload()

import io

df = pd.read_csv(io.BytesIO(uploaded['AAL.csv']))

df.head()

df = df.drop(['Date'], axis=1)
df.head()

df.isna().sum()

X = df.drop('Open', axis=1)
y = df['Open']
X.head()

model = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

openvalue = model.predict([[19.3, 150000, 21.65, 19.5, 18.9]])
print(openvalue)

print("Accuracy Score : ", model.score(X_test, y_test))

